services:
  api:
    build: ./app
    ports:
      - "3001:3000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    user: root   # 🔥 CLAVE (soluciona permission denied)
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: